project:
  type: website
  output-dir: docs

website:
  title: "soc490s"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - act_papers.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



