---
title: "Schedule"
---

+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Date     | Topic                                                             | Slides                                  | Prepare                                                                                                                               | Lab                                                                | Assignment                                                                                        |
+==========+===================================================================+=========================================+=======================================================================================================================================+====================================================================+===================================================================================================+
| 1/13     | Introduction                                                      | [💻](slides/jan_12.html#/title-slide)   | [Intro survey](https://duke.qualtrics.com/jfe/form/SV_bvyjiD0c1etSqxM)                                                                |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 1/18     | What is status?                                                   | [💻](slides/jan_18.pdf)                 | 1: [📖](readings/marx_wage_labor_capital.pdf)                                                                                         |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | 2: [📖](readings/weber_class_status_party.pdf "Weber")                                                                                |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 1/20     | How do we understand jobs/occupations sociologically?             | [💻](slides/jan_20.pdf)                 | [📖](readings/hughes_Social_Role_and_the_Division_of_Labor.pdf "Hughes")                                                              |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 1/25     | Why is measuring occupational status precisely important?         | [💻](slides/jan_25.pdf)                 | [📖](readings/haug_measurement_social_strat.pdf "Haug")                                                                               |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   | [Activity](labs/occupation_coding.docx) |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 1/27     | Introduction to Affect Control Theory                             | [💻](slides/jan_26.pdf)                 | [📖](readings/Heise-Expressive_Order_1_5.pdf "Heise")                                                                                 | [Lab: 📊](labs/soc490_Lab%201.docx)                                |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       | [Occs](resources/occs_dictionary.csv)                              |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       | [Dictionary](resources/occs_dictionary.csv)                        |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/1      | Occupations as identities -- role conflict                        |                                         | [📖](readings/boxed_in.pdf)                                                                                                           |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/3      | Affect Control Theory: Transient Impressions                      | [💻](slides/feb3.pdf)                   | [📖](readings/Heise-Expressive_Order_6_7.pdf "Heise 6-7")                                                                             |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/8      | Measuring occupational status, the cultural turn                  | [💻](slides/feb8.pdf)                   | [📖](readings/Freeland_Hoey2018The%20Structure%20of%20Deference.pdf "Freeland Hoey")                                                  |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/10     | Affect Control Theory: Deflection                                 | [💻](slides/feb_10.pdf)                 | [📖](readings/Boyle_McKinzie2015Resolving%20Negative%20Affect%20and%20Restoring%20Meaning.pdf "Boyle McKinzie")                       | [Lab 2: 📊](labs/Lab%202.docx)                                     |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       | [Occs Text File](resources/occupations_dictionary_interact.txt)    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       | [Youtube tutorial on using Interact](https://youtu.be/MuWcRSZhbi4) |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       | DUE Feb 24 at 8 am to em.k.maloney\@duke.edu                       |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/15     | Are occupational status beliefs the same across everyone?         | [💻](slides/feb_15.pdf)                 | [📖](readings/Lynn_Ellerbach2017A%20Position%20with%20a%20View.pdf "Lynn Ellerbach")                                                  |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/17     | Affect Control Theory: Emotions, Optimal Behavior, Relabeling     | [💻](slides/feb17.pdf)                  | [📖](readings/Maloney%20-%202023%20-%20The%20Influence%20of%20Occupational%20Identity%20on%20Emotiona.pdf "Maloney")                  | [Lab 3: 📊](labs/Lab%203.docx)                                     |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | [📖](readings/Heise-Expressive_Order_8_9.pdf "Heise 8-9")                                                                             |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/22     | Gender composition and occupational status                        | [💻](slides/feb_22.pdf)                 | [📖](readings/Valentino2020The%20Segregation%20Premium.pdf "Valentino")                                                               | [Lab 3: 📊](labs/Lab%203.docx)                                     |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    | DUE March 1 at 8am to em.k.maloney\@duke.edu                       |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 2/24     | Research Project: Research Questions                              | [💻](slides/feb24.pdf)                  | [📖](readings/Booth et al_Chapters 3 and 4.pdf "RQ")                                                                                  |                                                                    | [Research Question Assignment✍️](assignments/Research Question Assignment.docx)                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    | Due on March 3                                                                                    |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/1      | Intra-occupation status processes                                 |                                         | [📖](readings/Wingfield2009Racializing%20the%20Glass%20Escalator.pdf "Wingfield")                                                     |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/3      | Research Project: How to conduct a literature review              |                                         |                                                                                                                                       |                                                                    | [Annotated Bibliography Assignment✍️](assignments/Annotated Bibliography Assignment.docx)         |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    | Due March 10                                                                                      |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/8      | Customer interactions                                             |                                         | [📖](readings/Storer2022Serving%20Like%20an%20Organization.pdf "Storer")                                                              |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/10     | Research Project: How to choose research method and analysis plan |                                         | Methods sections of at least two of the following:                                                                                    |                                                                    | Methods Plan Assignment ✍️                                                                        |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | [📖](readings/Francis_Alinor2023Bereavement%20Adaptation%20as%20Deflection%20Reduction.pdf "Francis & Alinor")                        |                                                                    | Due March 22                                                                                      |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | [📖](readings/Soboroff%20and%20Kelley%20-%202023%20-%20Modeling%20Status%20Interventions%20with%20Affect%20Control%20.pdf "Soboroff") |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | [📖](readings/Robinson%201996%20Advances%20network%20friendship.pdf "Robinson")                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | [📖](readings/BergstrandJasper%202018%20SPQ%20Character%20Theory.pdf "Bergstrand")                                                    |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/15     | **Spring Break**                                                  |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/17     | **Spring Break**                                                  |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/22     | Peer edit methods plans                                           |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/24     | Mechanisms of Maintenance - Self/Identity                         |                                         | [📖](readings/Cech2013The%20Self-Expressive%20Edge%20of%20Occupational%20Sex%20Segregation.pdf "Cech")                                |                                                                    | [Literature Review Assignment ✍️](assignments/Literature%20Review%20Assignment.docx "Lit Review") |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    | Due March 31                                                                                      |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/29     | Mechanisms of Maintenance - Culture                               |                                         | [📖](readings/Explanations%20for%20occupational%20segregation: "Rivera")                                                              |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 3/31     | No Class                                                          |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/5      | How do some occupations become professions?                       |                                         | [📖](readings/liu2013.pdf "Liu")                                                                                                      |                                                                    | Methods/Results Section ✍️                                                                        |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    | Due April 7                                                                                       |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/7      | How does economic inequality in occupations emerge?               |                                         | [📖](readings/Weeden2002Why%20Do%20Some%20Occupations%20Pay%20More%20than%20Others.pdf "Weeden")                                      |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/12     | The double-bind of vocations                                      |                                         | [📖](readings/Bunderson_Thompson2009The%20Call%20of%20the%20Wild.pdf "Bunderson")                                                     |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/14     | Algorithms                                                        |                                         | [📖](readings/0730888417726119.pdf)                                                                                                   |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | Ann Bib entry in class google doc:                                                                                                    |                                                                    |                                                                                                   |
|          |                                                                   |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
|          |                                                                   |                                         | -   [link](https://docs.google.com/document/d/17zDg9zBFoUX9DIuO8OkbXfYuRhQD65QASnGmhkiO5bw/edit?usp=sharing)                          |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/19     | Work day                                                          |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/21     | Peer Edit full drafts of paper                                    |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| 4/26     | LDOC                                                              |                                         |                                                                                                                                       |                                                                    |                                                                                                   |
+----------+-------------------------------------------------------------------+-----------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
