---
title: "Sociology 490-S"
format:
  revealjs: 
    theme: default
editor: visual
execute:
  freeze: auto
---

## Meet your Instructor(s)

-   Prof Smith-Lovin

    -   will handle grading

-   Em Maloney

    -   will lecture and be primary course instructor

## Introductions

-   Name

-   Year

-   Job you would hate to have

-   Job you would love to have

## Activity

-   <https://emkmaloney.shinyapps.io/occprestige/>

## Syllabus

-   Course website: <https://ekmaloney.github.io/soc490s/>

-   **All** readings, labs, and assignments are located here!

-   Bookmark it!

## Course Objectives

-   Assess different methods of measuring occupational status and tie them to relevant social theorists' paradigms

-   Design a research project on a topic related to occupations and status

-   Understand the basic tenets of Affect Control Theory and apply them to substantive, original research on occupations

-   Demonstrate how being in differently valued occupations affects individuals' material, social, and emotional outcomes.

-   Interpret evidence for and against current debates in the sociology of work and status

## Course Structure

-   Synthesizing 3 goals:

    -   Occupations & Status literature

    -   Affect Control Theory

    -   Designing & Conducting research

## Course Structure

| Semester Period | Wednesdays                     | Fridays                      |
|-----------------|--------------------------------|------------------------------|
| First third     | Readings, Lectures, Activities | Affect Control Theory labs   |
| Second third    | Readings, Lectures, Activities | Research Project Assignments |
| Final third     | Readings, Lectures, Activities | Peer editing                 |

## Assessments

-   Participation (15%)

-   Labs (15%)

-   Assignments (20%)

-   Final Research Paper (40%)

## Final paper

-   Original research on a topic related to occupations and social status (broadly conceived)

-   Assignments lead up to it

-   Chance to incorporate feedback from instructors and peers

-   Semester constraints

## General Policies

-   Attendance is required **but** please do not come if you are sick!

-   If you know you will need to miss class in advance, please let us know as soon as possible

## General Policies

-   Late work is accepted **but** one letter grade decrease for every 24 hours it is late

    -   up to one day late = A

    -   up to two days late = A-

    -   up to three days late = B+

## General Policies

-   Academic Integrity

    -   please don't cheat

## Life Happens

-   You are adults, and I want to treat you as such.

-   **And** it is hard once you get behind to catch back up

-   We want you to succeed in this class

## Questions?
